[tools]
"zerobrew:gh" = "latest"
"zerobrew:glab" = "latest"
"zerobrew:ruby" = "latest"
"zerobrew:ripgrep" = "latest"
"zerobrew:fd" = "latest"
"zerobrew:wget" = "latest"
"zerobrew:vim" = "latest"
"zerobrew:micro" = "latest"
"zerobrew:nano" = "latest"
"zerobrew:python" = "latest"
"zerobrew:node" = "latest"
