[tools]
"github:cli/cli" = "latest"          # shim:gh
"github:jqlang/jq" = "latest"
"zerobrew:glab" = "latest"
"zerobrew:ruby" = "latest"
"github:BurntSushi/ripgrep" = "latest"  # shim:rg
"github:sharkdp/fd" = "latest"
"zerobrew:wget" = "latest"
"zerobrew:vim" = "latest"
"github:zyedidia/micro" = "latest"
"zerobrew:nano" = "latest"
"zerobrew:python" = "latest"
"node" = "latest"
"github:facebook/sapling" = "latest"    # shim:sl
